version: "3"

services:
  traefik:
    image: traefik
    container_name: traefik
    command:
    - "--api"
    - "--docker"
    - "--docker.swarmMode"
    - "--docker.domain=traefik"
    - "--docker.watch"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - traefik-net
    labels:
      traefik.port: 8080
      traefik.enable: true
      traefik.docker.network: traefik-net
      traefik.frontend.rule: "Host:www.owens.dev"
